### ISSUE TITLE
Does this work with mySQL?

### ISSUE THREAD

**Issue by ortonomy** [liquibase/liquibase-github-action#16]
I need to use this with mysql, but it doesn't work on my local install without download the mysql connector. is it possible with this action?

**Comment by AmitaiMazliah** [comment]
Any news on this? I also have the same issue

**Comment by jnewton03** [comment]
Hi @ortonomy / @AmitaiMazliah , we've been busy building out our new version of Github Actions.  However, those won't solve your use case.  Due to licensing we are not permitted to distribute the MySQL driver.  However, using the Liquibase Package Manager (LPM), you can install it.

What I'd recommend is using the liquibase docker container in your pipeline as that allows for customizations.  Like so:

```jobs:
  deploy-database-changes:
    runs-on: ubuntu-latest
    container:
      image: liquibase/liquibase:latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: lpm update && lpm add mysql

      - name: Update
        run: liquibase update --log-level SEVERE
```
