### ISSUE TITLE
Allow using the action with a proxy, that points to localhost

### ISSUE THREAD

**Issue by mathiaspet** [liquibase/liquibase-github-action#38]
Hi, 

I tried using the action in combination with the cloud sql proxy from GCP to connect to a Cloud SQL instance. The proxy opens a connection to localhost:5432 on the github runnner. I verified, that this works by using psql and a simple query. Unfortunatly, I cannot get the liquibase action to work as it fails to connect. I tried using `host.docker.internal` to no avail. When I ran the liquibase docker image locally. Worked. 

Do you have an idea, how to fix this?

**Comment by StevenMassaro** [comment]
I don't have any experience using the tools you're describing, but it sounds like you're running into an issue with docker networking. I wonder, are you using mac or windows for local testing?

If so, instead of using `host.docker.internal` can you try using `172.17.0.1`? That's a magic docker IP on linux that maps to the host, and I suspect that might work in GitHub actions.

See https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal
